# Generated by Django 4.2.1 on 2023-05-28 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FID', models.CharField(max_length=5)),
                ('origin', models.TextField()),
                ('destination', models.TextField()),
                ('depart', models.DateField()),
                ('dTime', models.TimeField(default=datetime.time(0, 0))),
                ('aTime', models.TimeField(default=datetime.time(0, 0))),
                ('roundTrip', models.BooleanField(default=False)),
                ('price', models.FloatField()),
            ],
        ),
    ]
