# Generated by Django 4.2.1 on 2023-05-28 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='roundTrip',
        ),
    ]
